# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170604_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='img_url',
            new_name='image',
        ),
    ]
